// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC886tQRWXtIMXTctCgdwUQ7qC0lldBtZ8',
    appId: '1:274324519250:web:b1af4918750a96542b228b',
    messagingSenderId: '274324519250',
    projectId: 'jobseasy-b4dfc',
    authDomain: 'jobseasy-b4dfc.firebaseapp.com',
    storageBucket: 'jobseasy-b4dfc.firebasestorage.app',
    measurementId: 'G-9581M3TW6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoLL3QMdWnZbbb8pHQ3Gs1eYeWtXPDWWw',
    appId: '1:274324519250:android:62aa5a818df9b83f2b228b',
    messagingSenderId: '274324519250',
    projectId: 'jobseasy-b4dfc',
    storageBucket: 'jobseasy-b4dfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdqLscROghmTSdmujZmCXJQGNdrNNRYSg',
    appId: '1:274324519250:ios:019f10c72246bfc22b228b',
    messagingSenderId: '274324519250',
    projectId: 'jobseasy-b4dfc',
    storageBucket: 'jobseasy-b4dfc.firebasestorage.app',
    iosClientId: '274324519250-cui5cl53lju7b0cqvpck7kgch06nheu6.apps.googleusercontent.com',
    iosBundleId: 'com.example.butterFly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdqLscROghmTSdmujZmCXJQGNdrNNRYSg',
    appId: '1:274324519250:ios:019f10c72246bfc22b228b',
    messagingSenderId: '274324519250',
    projectId: 'jobseasy-b4dfc',
    storageBucket: 'jobseasy-b4dfc.firebasestorage.app',
    iosClientId: '274324519250-cui5cl53lju7b0cqvpck7kgch06nheu6.apps.googleusercontent.com',
    iosBundleId: 'com.example.butterFly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC886tQRWXtIMXTctCgdwUQ7qC0lldBtZ8',
    appId: '1:274324519250:web:040444d3d419d8eb2b228b',
    messagingSenderId: '274324519250',
    projectId: 'jobseasy-b4dfc',
    authDomain: 'jobseasy-b4dfc.firebaseapp.com',
    storageBucket: 'jobseasy-b4dfc.firebasestorage.app',
    measurementId: 'G-61Q93NC2X7',
  );
}
